name: flutter_gakkai_20220129_monorepo

packages:
  - packages/**

scripts:
  get:all:
    run: |
      melos exec -c 1 -- \
        "flutter pub get

  analyze:
    run: |
      melos exec -- \
        "dart analyze . --fatal-infos"